title: PhotoSite
description: Photography portfolio
baseurl: "/photography"
url: "https://mattgravener99.github.io"

github_repo: "mattgravener99/photography"
github_branch: "main"
photos_path: "photos"

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
